### ISSUE TITLE
disconnect on join SMP after update to .100 -102

### ISSUE THREAD

**Issue by APolarBaer** [elucent/Roots#45]
[11:31:03] [Server thread/INFO]: APolarBaer joined the game
[11:31:03] [Server thread/INFO] [chancecubes]: No custom rewards detected for the current user!
[11:31:03] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[11:31:03] [Server thread/INFO] [Silent's Gems]: Recalculating tool and armor stats for APolarBaer
[11:31:03] [Server thread/INFO] [Waila]: Player EntityPlayerMP['APolarBaer'/3459, l='ArcticPackTest2', x=441.48, y=72.00, z=162.58] connected. Sending ping
[11:31:03] [Server thread/INFO] [mcjty.lib.varia.Logging]: SMP: Player logged in: Sync diminfo to clients
[11:31:03] [Server thread/INFO] [mcjty.lib.varia.Logging]: Sync dimension info to clients!
[11:31:03] [ForkJoinPool-1-worker-11/INFO] [OpenComputers]: Starting OpenComputers version check.
[11:31:03] [Server thread/INFO] [mcjty.lib.varia.Logging]: Send dimlet rules to the client
[11:31:03] [Server thread/INFO] [mcjty.lib.varia.Logging]: Rules packet size: 5531 of 8192
[11:31:03] [Server thread/INFO] [STDOUT]: [mcjty.lib.preferences.PreferencesProperties:syncToClient:31]: syncToClient: style = STYLE_FLAT_GRADIENT
[11:31:03] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$PlayerTickEvent@29710300:
java.lang.ClassCastException: elucent.roots.capability.RootsCapabilityManager$1ManaCapabilityProvider cannot be cast to mcjty.rftools.playerprops.PorterProperties
        at mcjty.rftools.playerprops.PlayerExtendedProperties.getPorterProperties(PlayerExtendedProperties.java:23) ~[PlayerExtendedProperties.class:?]
        at mcjty.rftools.ForgeEventHandlers.onPlayerTickEvent(ForgeEventHandlers.java:45) ~[ForgeEventHandlers.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_581_ForgeEventHandlers_onPlayerTickEvent_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:353) [FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:183) [zj.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) [ls.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163) [mc.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193) [NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) [em.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mb.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
[11:31:04] [Server thread/ERROR] [FML]: Index: 11 Listeners:
[11:31:04] [Server thread/ERROR] [FML]: 0: NORMAL
[11:31:04] [Server thread/ERROR] [FML]: 1: ASM: mcjty.lib.McJtyLib$EventHandler@24a8a83c onPlayerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 2: ASM: crazypants.enderio.item.darksteel.DarkSteelController@1f907f8f onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 3: ASM: crazypants.enderio.item.MagnetController@73f9c37b onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 4: ASM: de.intektor.modifiable_armor.event.MAEventHandler@6bf4d28c playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 5: ASM: sokratis12GR.ArmorPlus.resources.GlobalEventsArmorPlus@5976737c onArmorTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 6: ASM: com.enderio.core.common.handlers.FireworkHandler@6c02b4e6 onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 7: ASM: INSTANCE onPlayerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 8: ASM: de.intektor.lucky_cases.event.LCEventHandler@3a14cb8c playerTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 9: ASM: com.parachute.common.PlayerTickEventHandler@7092052b onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 10: ASM: mrdimka.playerstats.common.event.ModEvents@2fe3a8d5 playerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 11: ASM: mcjty.rftools.ForgeEventHandlers@76bf8152 onPlayerTickEvent(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 12: ASM: Block{botania:pistonRelay} tickEnd(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 13: ASM: org.cyclops.evilcraft.core.fluid.WorldSharedTankCache@1b7e594 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 14: ASM: lumien.randomthings.handler.RTEventHandler@17363a5c tick(Lnet/minecraftforge/fml/common/gameevent/TickEvent;)V
[11:31:04] [Server thread/ERROR] [FML]: 15: LOWEST
[11:31:04] [Server thread/ERROR] [FML]: 16: ASM: vazkii.botania.common.item.ItemRegenIvy@6baba1a7 onTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[11:31:04] [Server thread/WARN]: Failed to handle packet for /99.254.194.143:62524
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:380) ~[ls.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:163) ~[mc.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:193) ~[NetworkDispatcher$1.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[em.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [mb.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:730) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385) [lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.ClassCastException: elucent.roots.capability.RootsCapabilityManager$1ManaCapabilityProvider cannot be cast to mcjty.rftools.playerprops.PorterProperties
        at mcjty.rftools.playerprops.PlayerExtendedProperties.getPorterProperties(PlayerExtendedProperties.java:23) ~[PlayerExtendedProperties.class:?]
        at mcjty.rftools.ForgeEventHandlers.onPlayerTickEvent(ForgeEventHandlers.java:45) ~[ForgeEventHandlers.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_581_ForgeEventHandlers_onPlayerTickEvent_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:353) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:183) ~[zj.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[ls.class:?]
        ... 9 more
[11:31:04] [ForkJoinPool-1-worker-11/INFO] [OpenComputers]: Running the latest OpenComputers version.
[11:31:04] [Server thread/INFO]: APolarBaer lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[11:31:04] [Server thread/INFO]: APolarBaer left the game

**Comment by APolarBaer** [comment]
reverted to .007 and i can log in again, rip cool update DX

**Comment by elucent** [comment]
There's a bug with the capabilities, they're new and I'm still figuring them out. Hopefully it's a stupid mistake and it should be an easy fix.

**Comment by APolarBaer** [comment]
no worries, really excited for the new update, sounds soo cool. love the mod keep up the good work owo

**Comment by elucent** [comment]
I think I fixed it, made a really stupid mistake with the getCapability function. I'll test it.

**Comment by elucent** [comment]
It worked! Releasing fix now.

**Comment by APolarBaer** [comment]
thank you for your quick work~ cant wait to see the new stuff and what lies ahead

**Comment by APolarBaer** [comment]
Confirm fixed for my pack at least, thanks again~
