### ISSUE TITLE
Crash from Staff imbued with Devils Flower

### ISSUE THREAD

**Issue by wylker** [elucent/Roots#68]
[16:18:50] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingSetAttackTargetEvent@3a901887:
java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:93) ~[Event.class:?]
	at elucent.roots.EventManager.onLivingTarget(EventManager.java:106) ~[EventManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_303_EventManager_onLivingTarget_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:486) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:173) [sg.class:?]
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75249_e(SourceFile:110) [ve.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) [tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:770) [sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2190) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) [sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47) [yx.class:?]
	at net.minecraft.entity.monster.EntitySkeleton.func_70636_d(SourceFile:184) [zd.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020) [sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) [sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52) [yx.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1962) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) [ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1932) [aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1748) [aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) [ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
[16:18:50] [Server thread/ERROR] [FML]: Index: 1 Listeners:
[16:18:50] [Server thread/ERROR] [FML]: 0: NORMAL
[16:18:50] [Server thread/ERROR] [FML]: 1: ASM: elucent.roots.EventManager@658ebe onLivingTarget(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[16:18:50] [Server thread/ERROR] [FML]: 2: ASM: xreliquary.handler.CommonEventHandler@776dcef9 onEntityTargetedEvent(Lnet/minecraftforge/event/entity/living/LivingSetAttackTargetEvent;)V
[16:18:50] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:715) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Attempted to cancel a non cancellable event
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:93) ~[Event.class:?]
	at elucent.roots.EventManager.onLivingTarget(EventManager.java:106) ~[EventManager.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_303_EventManager_onLivingTarget_LivingSetAttackTargetEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:72) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:168) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingSetAttackTarget(ForgeHooks.java:486) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLiving.func_70624_b(EntityLiving.java:173) ~[sg.class:?]
	at net.minecraft.entity.ai.EntityAINearestAttackableTarget.func_75249_e(SourceFile:110) ~[ve.class:?]
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:102) ~[tr.class:?]
	at net.minecraft.entity.EntityLiving.func_70626_be(EntityLiving.java:770) ~[sg.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2190) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:577) ~[sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70636_d(SourceFile:47) ~[yx.class:?]
	at net.minecraft.entity.monster.EntitySkeleton.func_70636_d(SourceFile:184) ~[zd.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2020) ~[sf.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:295) ~[sg.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70071_h_(SourceFile:52) ~[yx.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1962) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837) ~[ls.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1932) ~[aid.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1748) ~[aid.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618) ~[ls.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709) ~[MinecraftServer.class:?]
	... 4 more
[16:18:50] [Server thread/ERROR]: This crash report has been saved to: /home/gp/1221/userdata/FTB-Unstable/./crash-reports/crash-2016-07-19_16.18.50-server.txt
[16:18:50] [Server thread/INFO]: Stopping server

**Comment by wylker** [comment]
Forge 2014 and Roots .107

**Comment by elucent** [comment]
Update to a more recent version, this has already been fixed.
